language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mantaskujalis/multi-docker-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mantaskujalis/multi-docker-client-test npm test -- --coverage

after_success:
  - docker build -t mantaskujalis/multi-docker-client ./client
  - docker build -t mantaskujalis/multi-docker-worker ./worker
  - docker build -t mantaskujalis/multi-docker-nginx ./nginx
  - docker build -t mantaskujalis/multi-docker-server ./server

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push mantaskujalis/multi-docker-client
  - docker push mantaskujalis/multi-docker-worker
  - docker push mantaskujalis/multi-docker-nginx
  - docker push mantaskujalis/multi-docker-server

